import { Link, useLocation } from "react-router-dom";
import { usePageMeta } from "../hooks/usePageMeta";

const policyUpdated = { dateTime: "2026-09-20", label: "Last updated 20 September 2026" };
const pages: Record<string, { title: string; intro: string; sections: Array<[string, string]>; updated?: typeof policyUpdated }> = {
  "/about": { title: "About Fieldio", intro: "Fieldio is an independent designer fashion marketplace and personal shopping service operating at fieldio.shop.", sections: [["What is Fieldio?", "Fieldio helps customers discover and request clothing, footwear, and accessories from designer, luxury, sportswear, and everyday fashion brands."], ["How does Fieldio work?", "Customers can browse the live edit or ask a personal shopper to source a specific piece. Availability, condition, final price, shipping, and payment are confirmed before an order is accepted."], ["Who can sell on Fieldio?", "Approved independent boutiques, collectors, and vendors can submit authentic fashion for review before it is published."], ["Where does Fieldio deliver?", "Fieldio coordinates worldwide delivery where carrier and customs rules permit, with timing and duties guidance confirmed for each request."]] },
  "/promise": { title: "The Fieldio Promise", intro: "Clear information, reviewed sellers, and direct support from request to delivery.", sections: [["Verified sellers", "Sellers provide identity and address evidence before they can create a store. Business vendors also provide registration evidence. Fieldio reviews the application and may pause access when information changes or concerns arise."], ["Reviewed listings", "Seller products do not publish automatically. Fieldio reviews the description, condition, ownership declaration, images, and product details before approving a listing."], ["Authenticity", "Sellers must declare that every listed item is authentic and that they are authorised to sell it. Fieldio reviews the supplied evidence, but customers should request any additional proof they need before payment."], ["Condition standards", "New items are unused, with tags noted separately. Excellent shows minimal wear. Very Good shows light visible wear. Good shows visible wear that is clearly described. Fair shows significant disclosed wear while remaining usable."], ["Sourcing", "For personally sourced pieces, Fieldio confirms the exact product, condition, availability, final price, and applicable return terms before payment."], ["Delivery and support", "Delivery estimates, carrier options, duties guidance, and payment arrangements are confirmed for each request. Customers can continue the conversation on WhatsApp from their account order history."]] },
  "/how-it-works": { title: "How Fieldio works", intro: "A direct path from discovery to a confirmed fashion request—without taking payment before the details are agreed.", sections: [["Browse or ask", "Explore the live edit, save pieces to your wishlist, or send Fieldio a product link, screenshot, name, size, or sourcing brief."], ["Send a request", "Choose a size and add the piece to your bag. Checkout creates an order request and opens a prepared WhatsApp conversation; it does not charge you or guarantee stock."], ["Confirm the details", "Fieldio confirms availability, condition, authenticity information, final price, delivery estimate, duties guidance, return eligibility, and the available payment arrangement."], ["Approve and pay", "Only continue after you are satisfied with the confirmed product and terms. Payment is arranged directly after confirmation; no payment gateway is used on the website."], ["Follow delivery", "Signed-in customers can view the request status and continue the WhatsApp conversation from their account until delivery."]] },
  "/shipping": { title: "Shipping policy", intro: "Shipping is confirmed for each order request before payment.", updated: policyUpdated, sections: [["Destinations", "Fieldio supports worldwide shipment where carrier and customs rules permit."], ["Timing", "Dispatch estimates begin after availability, payment, and any sourcing lead time are confirmed."], ["Duties", "Customs duties and import taxes may apply and will be explained where known before purchase."]] },
  "/returns": { title: "Returns policy", intro: "Return eligibility depends on the item, source, and condition and is confirmed before payment.", updated: policyUpdated, sections: [["Before purchase", "Fieldio will state the applicable return terms in the WhatsApp purchase conversation."], ["Condition", "Approved returns must remain unused with original packaging and tags."], ["Exceptions", "Personalised, hygiene-sensitive, final-sale, and specially sourced products may not be returnable."]] },
  "/privacy": { title: "Privacy policy", intro: "Fieldio collects only the information needed to answer enquiries, manage order requests, and provide opted-in updates.", updated: policyUpdated, sections: [["Information", "We may process contact details, shipping information, enquiry content, account data, seller verification evidence, and order-request history."], ["Use", "Information is used to provide services, review sellers and listings, protect the platform, and send marketing only where consent exists."], ["Seller data", "Deleting an account removes its seller verification documents, private listing media, and seller products. Linked order-request records are anonymised and may be retained only where needed for legal, tax, fraud-prevention, or dispute duties."], ["Control", "You can request access or correction, delete your account from Account details, or unsubscribe from marketing at any time."]] },
  "/terms": { title: "Terms", intro: "Using Fieldio means accepting these launch-stage service terms.", updated: policyUpdated, sections: [["Order requests", "A website or WhatsApp request is not an accepted order, stock confirmation, or payment receipt."], ["Confirmation", "A purchase becomes confirmed only after Fieldio confirms the item, total cost, shipping, and payment terms."], ["Product information", "Final brand, condition, dimensions, materials, and care details are confirmed before payment for sourced products."]] },
  "/cookies": { title: "Cookie policy", intro: "Fieldio uses essential storage for cart, wishlist, theme-safe rendering, and account sessions.", updated: policyUpdated, sections: [["Essential storage", "Local storage keeps your bag and wishlist on your device."], ["Analytics", "Optional analytics is loaded only after you choose Allow. Campaign attribution reads only standard UTM parameters, is not stored by Fieldio in your browser, and is sent only after consent."], ["Control", "You can clear stored site data through your browser settings."]] }
};

export function ContentPage() {
  const { pathname } = useLocation();
  const page = pages[pathname] ?? pages["/about"]!;
  usePageMeta({ title: pathname === "/about" ? "About Fieldio | Designer Fashion Marketplace" : `${page.title} | Fieldio`, description: page.intro, canonical: `https://fieldio.shop${pathname}` });
  return <article className="content-page"><header><h1>{page.title}</h1><p>{page.intro}</p></header>{page.updated && <time className="policy-date" dateTime={page.updated.dateTime}>{page.updated.label}</time>}<div className="content-sections">{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div>{page.updated && <p className="policy-note">This launch-stage policy copy should be reviewed by Fieldio’s legal adviser before a final effective date is published.</p>}<Link to="/contact" className="text-link">Contact Fieldio</Link></article>;
}
