import { Link, useLocation } from "react-router-dom";
import { usePageMeta } from "../hooks/usePageMeta";

const pages: Record<string, { title: string; intro: string; sections: Array<[string, string]> }> = {
  "/about": { title: "Everything fashion.", intro: "Fieldio is a personal-shopping, fashion, and supply service built around direct support and worldwide shipment.", sections: [["A considered search", "We help customers find specific fashion pieces across luxury, sportswear, accessories, and everyday wardrobes."], ["Direct confirmation", "Availability, authenticity, condition, shipping, and payment are confirmed in conversation before a request becomes an order."], ["Worldwide service", "Delivery options and timings are confirmed for each destination and sourced piece."]] },
  "/shipping": { title: "Shipping policy", intro: "Shipping is confirmed for each order request before payment.", sections: [["Destinations", "Fieldio supports worldwide shipment where carrier and customs rules permit."], ["Timing", "Dispatch estimates begin after availability, payment, and any sourcing lead time are confirmed."], ["Duties", "Customs duties and import taxes may apply and will be explained where known before purchase."]] },
  "/returns": { title: "Returns policy", intro: "Return eligibility depends on the item, source, and condition and is confirmed before payment.", sections: [["Before purchase", "Fieldio will state the applicable return terms in the WhatsApp purchase conversation."], ["Condition", "Approved returns must remain unused with original packaging and tags."], ["Exceptions", "Personalised, hygiene-sensitive, final-sale, and specially sourced products may not be returnable."]] },
  "/privacy": { title: "Privacy policy", intro: "Fieldio collects only the information needed to answer enquiries, manage order requests, and provide opted-in updates.", sections: [["Information", "We may process contact details, shipping information, enquiry content, account data, and order-request history."], ["Use", "Information is used to provide services, protect the platform, and send marketing only where consent exists."], ["Control", "You can request access, correction, deletion, or unsubscribe from marketing by contacting Fieldio."]] },
  "/terms": { title: "Terms", intro: "Using Fieldio means accepting these launch-stage service terms.", sections: [["Order requests", "A website or WhatsApp request is not an accepted order, stock confirmation, or payment receipt."], ["Confirmation", "A purchase becomes confirmed only after Fieldio confirms the item, total cost, shipping, and payment terms."], ["Product information", "Final brand, condition, dimensions, materials, and care details are confirmed before payment for sourced products."]] },
  "/cookies": { title: "Cookie policy", intro: "Fieldio uses essential storage for cart, wishlist, theme-safe rendering, and account sessions.", sections: [["Essential storage", "Local storage keeps your bag and wishlist on your device."], ["Analytics", "Optional analytics should be enabled only with appropriate consent controls."], ["Control", "You can clear stored site data through your browser settings."]] }
};

export function ContentPage() {
  const { pathname } = useLocation();
  const page = pages[pathname] ?? pages["/about"]!;
  usePageMeta({ title: `${page.title} | Fieldio`, description: page.intro, canonical: `https://fieldio.shop${pathname}` });
  return <article className="content-page"><header><h1>{page.title}</h1><p>{page.intro}</p></header><div className="content-sections">{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div><p className="policy-note">This launch-ready policy copy should be reviewed by Fieldio’s legal adviser for the final operating countries and business entity.</p><Link to="/contact" className="text-link">Contact Fieldio</Link></article>;
}
