drop policy if exists "admins delete product image objects" on storage.objects;
drop policy if exists "admins update product image objects" on storage.objects;
drop policy if exists "admins upload product image objects" on storage.objects;
drop policy if exists "public read product image objects" on storage.objects;
delete from storage.buckets where id = 'product-images';
drop table if exists public.audit_logs cascade;
drop table if exists public.editorial_content cascade;
drop table if exists public.wholesale_inquiries cascade;
drop table if exists public.contact_messages cascade;
drop table if exists public.newsletter_subscribers cascade;
drop table if exists public.order_items cascade;
drop table if exists public.order_requests cascade;
drop sequence if exists public.order_reference_seq;
drop table if exists public.addresses cascade;
drop table if exists public.wishlist_items cascade;
drop table if exists public.wishlists cascade;
drop table if exists public.cart_items cascade;
drop table if exists public.carts cascade;
drop table if exists public.collection_products cascade;
drop table if exists public.inventory cascade;
drop table if exists public.product_variants cascade;
drop table if exists public.product_images cascade;
drop table if exists public.products cascade;
drop table if exists public.collections cascade;
drop table if exists public.categories cascade;
drop table if exists public.brands cascade;
drop function if exists public.is_owner();
drop function if exists public.is_admin();
drop table if exists public.admin_users cascade;
drop table if exists public.profiles cascade;
drop function if exists public.handle_new_user();
drop function if exists public.set_updated_at();
drop type if exists public.subscriber_status;
drop type if exists public.order_request_status;
drop type if exists public.product_status;
