begin;
drop policy if exists "review owners upload reserved media" on storage.objects;
drop policy if exists "public reads review media" on storage.objects;
delete from storage.buckets where id = 'review-media' and not exists (select 1 from storage.objects where bucket_id = 'review-media');
drop function if exists public.moderate_product_review(uuid, text, text);
drop function if exists public.report_product_review(uuid, text);
drop function if exists public.toggle_review_helpful(uuid);
drop function if exists public.reserve_review_image(uuid, text);
drop function if exists public.update_product_review(uuid, integer, text, text[]);
drop function if exists public.create_product_review(uuid, integer, text, text[]);
drop function if exists public.review_eligibility(uuid);
drop function if exists public.product_review_summary(uuid);
drop function if exists public.seller_review_summary();
drop function if exists public.refresh_review_has_photos();
drop function if exists public.refresh_review_helpful_count();
drop function if exists public.refresh_product_rating_trigger();
drop function if exists public.refresh_product_rating(uuid);
drop table if exists public.product_review_reports;
drop table if exists public.product_review_helpful;
drop table if exists public.product_review_images;
drop table if exists public.product_reviews;
alter table public.products drop column if exists rating_count, drop column if exists average_rating;
commit;
