begin;
drop function if exists public.update_seller_payout(uuid,text,text);
drop function if exists public.create_seller_payout(uuid,text);
drop function if exists public.accept_admin_invitation(text);
drop trigger if exists refresh_fulfillment_financials_after_item on public.order_items;
drop function if exists public.refresh_fulfillment_financials();
drop trigger if exists mark_fulfillment_payout_eligibility on public.order_fulfillments;
drop function if exists public.mark_fulfillment_payout_eligibility();
drop table if exists public.marketplace_disputes;
drop table if exists public.marketplace_returns;
drop table if exists public.seller_payout_items;
drop table if exists public.seller_payouts;
drop table if exists public.email_campaign_recipients;
drop table if exists public.email_campaigns;
drop table if exists public.admin_invitations;
alter table public.order_fulfillments drop column if exists payout_status, drop column if exists vendor_net_amount, drop column if exists commission_amount, drop column if exists gross_amount, drop column if exists commission_rate_bps;
drop index if exists public.admin_users_email_idx;
alter table public.admin_users drop column if exists email;
commit;
